/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:923438fd-5aa4-4782-a86e-ea25587c3a1e",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_WKYVxUx3Q",
    "aws_user_pools_web_client_id": "5fl69ale1ucbo8qhiqn7suqknb",
    "oauth": {}
};


export default awsmobile;
